import { useState, useEffect } from 'react';
import { Plus, Edit, Trash2, Save, X } from 'lucide-react';
import { useToast } from '../../components/common/Toast';
const API='http://localhost:8080/api/v1'; const h=()=>({'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('auth_token')}`});
export default function ProductManager(){const[list,setList]=useState<any[]>([]);const[edit,setEdit]=useState<any>(null);const{showToast}=useToast();
const load=async()=>{const r=await fetch(`${API}/products/all`,{headers:h()});setList((await r.json()).data||[]);};
useEffect(()=>{load();},[]);
const save=async()=>{if(!edit)return;const m=edit.id?'PUT':'POST';const url=edit.id?`${API}/products/${edit.id}`:`${API}/products`;await fetch(url,{method:m,headers:h(),body:JSON.stringify({...edit,features:typeof edit.features==='string'?edit.features.split(','):edit.features||[]})});showToast('success',edit.id?'更新成功':'创建成功');setEdit(null);load();};
const del=async(id:number)=>{if(!confirm('确定删除?'))return;await fetch(`${API}/products/${id}`,{method:'DELETE',headers:h()});showToast('success','已删除');load();};
return(<div><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold text-gray-900">产品管理</h1><button onClick={()=>setEdit({name:'',category:'general',description:'',features:[],icon:'Server',published:true,sort:0})} className="flex items-center gap-2 px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary-600 text-sm"><Plus className="w-4 h-4"/>新增产品</button></div>
{edit!==null&&(<div className="fixed inset-0 bg-black/30 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg p-6 max-h-[90vh] overflow-y-auto"><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-bold">{edit.id?'编辑产品':'新增产品'}</h2><button onClick={()=>setEdit(null)}><X className="w-5 h-5"/></button></div><div className="space-y-3">{[{k:'name',l:'名称'},{k:'category',l:'分类(general/ai/integration/ops)'},{k:'description',l:'描述'},{k:'features',l:'特性(逗号分隔)'},{k:'icon',l:'图标名'}].map((f)=>(<div key={f.k}><label className="block text-xs font-medium text-gray-600 mb-1">{f.l}</label><input value={(edit as any)[f.k]||''} onChange={e=>setEdit({...edit,[f.k]:e.target.value})} className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"/></div>))}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={edit.published??1} onChange={e=>setEdit({...edit,published:e.target.checked?1:0})}/>发布</label></div><div className="flex justify-end gap-3 mt-6"><button onClick={()=>setEdit(null)} className="px-4 py-2 border border-gray-200 rounded-lg text-sm">取消</button><button onClick={save} className="px-4 py-2 bg-primary text-white rounded-lg text-sm flex items-center gap-2"><Save className="w-4 h-4"/>保存</button></div></div></div>)}
<div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><table className="w-full text-sm"><thead className="bg-gray-50 border-b"><tr><th className="text-left px-4 py-3">名称</th><th className="text-left px-4 py-3">分类</th><th className="text-left px-4 py-3">状态</th><th className="text-right px-4 py-3">操作</th></tr></thead><tbody>{list.map((p)=>(<tr key={p.id} className="border-b border-gray-50"><td className="px-4 py-3">{p.name}</td><td className="px-4 py-3 text-xs text-gray-500">{p.category}</td><td className="px-4 py-3"><span className={`text-xs px-2 py-0.5 rounded-full ${p.published?'bg-green-50 text-green-600':'bg-gray-100 text-gray-500'}`}>{p.published?'已发布':'下架'}</span></td><td className="px-4 py-3 text-right"><button onClick={()=>setEdit({...p,features:(p.features||[]).join(',')})} className="p-1.5 hover:bg-gray-100 rounded text-gray-500"><Edit className="w-4 h-4"/></button><button onClick={()=>del(p.id)} className="p-1.5 hover:bg-red-50 rounded text-red-500"><Trash2 className="w-4 h-4"/></button></td></tr>))}</tbody></table></div></div>);}
