import { useState, useEffect } from 'react';
import { Plus, Edit, Trash2, Save, X } from 'lucide-react';
import { useToast } from '../../components/common/Toast';
const API='http://localhost:8080/api/v1'; const h=()=>({'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('auth_token')}`});

interface Props { title: string; endpoint: string; fields: {key:string;label:string;type?:string;opts?:{v:string;l:string}[]}[]; }

export default function SimpleManager({ title, endpoint, fields }: Props) {
  const [list, setList] = useState<any[]>([]); const [edit, setEdit] = useState<any>(null); const {showToast}=useToast();
  const load=async()=>{const r=await fetch(`${API}/${endpoint}`,{headers:h()});setList((await r.json()).data||[]);};
  useEffect(()=>{load();},[]);
  const save=async()=>{if(!edit)return;const m=edit.id?'PUT':'POST';const url=edit.id?`${API}/${endpoint}/${edit.id}`:`${API}/${endpoint}`;await fetch(url,{method:m,headers:h(),body:JSON.stringify(edit)});showToast('success','保存成功');setEdit(null);load();};
  const del=async(id:number)=>{if(!confirm('确定删除?'))return;await fetch(`${API}/${endpoint}/${id}`,{method:'DELETE',headers:h()});showToast('success','已删除');load();};
  return(<div><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold text-gray-900">{title}</h1><button onClick={()=>{const o:any={};fields.forEach(f=>o[f.key]='');setEdit(o)}} className="flex items-center gap-2 px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary-600 text-sm"><Plus className="w-4 h-4"/>新增</button></div>
  {edit!==null&&(<div className="fixed inset-0 bg-black/30 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg p-6"><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-bold">{edit.id?'编辑':'新增'}</h2><button onClick={()=>setEdit(null)}><X className="w-5 h-5"/></button></div><div className="space-y-3">{fields.map(f=>(<div key={f.key}><label className="block text-xs font-medium text-gray-600 mb-1">{f.label}</label>{f.type==='select'?<select value={edit[f.key]||''} onChange={e=>setEdit({...edit,[f.key]:e.target.value})} className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm">{f.opts?.map(o=><option key={o.v} value={o.v}>{o.l}</option>)}</select>:<input value={edit[f.key]||''} onChange={e=>setEdit({...edit,[f.key]:e.target.value})} className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"/>}</div>))}</div><div className="flex justify-end gap-3 mt-6"><button onClick={()=>setEdit(null)} className="px-4 py-2 border border-gray-200 rounded-lg text-sm">取消</button><button onClick={save} className="px-4 py-2 bg-primary text-white rounded-lg text-sm flex items-center gap-2"><Save className="w-4 h-4"/>保存</button></div></div></div>)}
  <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><table className="w-full text-sm"><thead className="bg-gray-50 border-b"><tr>{fields.slice(0,3).map(f=><th key={f.key} className="text-left px-4 py-3">{f.label}</th>)}<th className="text-right px-4 py-3">操作</th></tr></thead><tbody>{list.map((item)=>(<tr key={item.id||item.key} className="border-b border-gray-50">{fields.slice(0,3).map(f=><td key={f.key} className="px-4 py-3">{item[f.key]?.slice?.(0,50)||item[f.key]}</td>)}<td className="px-4 py-3 text-right"><button onClick={()=>setEdit(item)} className="p-1.5 hover:bg-gray-100 rounded text-gray-500"><Edit className="w-4 h-4"/></button><button onClick={()=>del(item.id)} className="p-1.5 hover:bg-red-50 rounded text-red-500"><Trash2 className="w-4 h-4"/></button></td></tr>))}</tbody></table></div></div>);
}
